# Generated by Django 4.2.7 on 2025-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_prescription_diagnosis_id_prescription_encounter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis_code',
            field=models.CharField(blank=True, help_text='Mã chẩn đoán (ICD-10)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis_description',
            field=models.TextField(blank=True, help_text='Mô tả chẩn đoán', null=True),
        ),
    ]
