# Generated by Django 4.2.7 on 2025-04-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='lab_test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='medical_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='prescription_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up Visit'), ('EMERGENCY', 'Emergency Visit'), ('PROCEDURE', 'Medical Procedure'), ('SURGERY', 'Surgery'), ('IMAGING', 'Imaging (X-ray, MRI, etc.)'), ('VACCINATION', 'Vaccination'), ('LAB_TEST', 'Laboratory Test'), ('BLOOD_TEST', 'Blood Test'), ('URINE_TEST', 'Urine Test'), ('PATHOLOGY', 'Pathology'), ('MEDICATION', 'Medication'), ('PRESCRIPTION', 'Prescription'), ('OTC_MEDICATION', 'Over-the-counter Medication'), ('MEDICAL_SUPPLY', 'Medical Supply'), ('ROOM_CHARGE', 'Room Charge'), ('ICU_CHARGE', 'ICU Charge'), ('WARD_CHARGE', 'Ward Charge'), ('ADMINISTRATIVE', 'Administrative Fee'), ('INSURANCE', 'Insurance Processing'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
