# Generated by Django 4.2.7 on 2025-04-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceitem_appointment_id_invoiceitem_lab_test_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='member_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
