# Generated by Django 4.2.7 on 2025-04-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_insuranceclaim_claim_amount_insuranceclaim_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment gateway used for processing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference code from payment gateway', max_length=100, null=True),
        ),
    ]
