# Generated by Django 4.2.7 on 2025-04-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField()),
                ('recipient_type', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('ADMIN', 'Administrator'), ('PHARMACIST', 'Pharmacist'), ('INSURANCE_PROVIDER', 'Insurance Provider'), ('LAB_TECHNICIAN', 'Laboratory Technician'), ('OTHER', 'Other')], max_length=20)),
                ('notification_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('BILLING', 'Billing'), ('MEDICAL_RECORD', 'Medical Record'), ('LAB_RESULT', 'Lab Result'), ('PRESCRIPTION', 'Prescription'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], default='UNREAD', max_length=10)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_id', 'recipient_type'], name='notificatio_recipie_cb6515_idx'), models.Index(fields=['status'], name='notificatio_status_ae9db4_idx'), models.Index(fields=['created_at'], name='notificatio_created_e7628e_idx')],
            },
        ),
    ]
