# Generated by Django 4.2.7 on 2025-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='appointment_id',
            field=models.IntegerField(blank=True, help_text='ID của cuộc hẹn trong appointment-service', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text='Lý do khám chính', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('EMERGENCY', 'Emergency'), ('FOLLOWUP', 'Follow-up'), ('TELECONSULTATION', 'Teleconsultation')], default='OUTPATIENT', max_length=20),
        ),
    ]
