# Generated by Django 4.2.7 on 2025-04-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_labtest_lab_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Specimen Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20),
        ),
    ]
