# Generated by Django 4.2.7 on 2025-04-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID của bệnh nhân trong user-service')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CHECKED_IN', 'Đã check-in'), ('IN_PROGRESS', 'Đang khám'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy'), ('NO_SHOW', 'Không đến'), ('RESCHEDULED', 'Đã đổi lịch')], default='PENDING', max_length=20)),
                ('appointment_type', models.CharField(choices=[('REGULAR', 'Khám thông thường'), ('FOLLOW_UP', 'Tái khám'), ('EMERGENCY', 'Cấp cứu'), ('CONSULTATION', 'Tư vấn')], default='REGULAR', max_length=20)),
                ('priority', models.IntegerField(choices=[(0, 'Thông thường'), (1, 'Ưu tiên'), (2, 'Khẩn cấp')], default=0)),
                ('reason_text', models.TextField(blank=True, help_text='Lý do khám chi tiết', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, help_text='Mẫu lặp lại (ví dụ: weekly, monthly)', max_length=50, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medical_record_id', models.IntegerField(blank=True, help_text='ID hồ sơ y tế liên quan', null=True)),
                ('insurance_id', models.CharField(blank=True, help_text='Mã bảo hiểm', max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, help_text='ID người tạo lịch hẹn', null=True)),
                ('prescription_id', models.IntegerField(blank=True, help_text='ID đơn thuốc liên quan', null=True)),
                ('lab_request_id', models.IntegerField(blank=True, help_text='ID yêu cầu xét nghiệm liên quan', null=True)),
                ('billing_id', models.IntegerField(blank=True, help_text='ID hóa đơn liên quan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='appointments.appointment')),
                ('parent_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_appointments', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['time_slot__date', 'time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên lý do khám', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết', null=True)),
                ('department', models.CharField(blank=True, help_text='Khoa/Phòng liên quan', max_length=100, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Mức độ ưu tiên (cao hơn = ưu tiên hơn)')),
                ('estimated_duration', models.IntegerField(default=30, help_text='Thời gian ước tính (phút)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Reason',
                'verbose_name_plural': 'Appointment Reasons',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(help_text='ID của bác sĩ trong user-service')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Ngày trong tuần (0: Thứ 2, 6: Chủ nhật)')),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu làm việc')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc làm việc')),
                ('is_available', models.BooleanField(default=True, help_text='Trạng thái hoạt động của lịch làm việc')),
                ('location', models.CharField(blank=True, help_text='Địa điểm làm việc', max_length=255, null=True)),
                ('department', models.CharField(blank=True, help_text='Khoa/Phòng', max_length=100, null=True)),
                ('room', models.CharField(blank=True, help_text='Phòng khám', max_length=50, null=True)),
                ('schedule_type', models.CharField(choices=[('REGULAR', 'Lịch thường xuyên'), ('TEMPORARY', 'Lịch tạm thời'), ('DAY_OFF', 'Nghỉ phép')], default='REGULAR', help_text='Loại lịch làm việc', max_length=20)),
                ('effective_date', models.DateField(blank=True, help_text='Ngày áp dụng (cho lịch tạm thời hoặc nghỉ phép)', null=True)),
                ('slot_duration', models.IntegerField(default=30, help_text='Thời lượng mỗi khung giờ (phút)')),
                ('max_patients_per_slot', models.IntegerField(default=1, help_text='Số lượng bệnh nhân tối đa cho mỗi khung giờ')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'unique_together': {('doctor_id', 'weekday', 'start_time', 'end_time', 'schedule_type', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(help_text='ID của bác sĩ trong user-service')),
                ('date', models.DateField(help_text='Ngày khám')),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc')),
                ('is_available', models.BooleanField(default=True, help_text='Khung giờ có sẵn sàng không')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('BOOKED', 'Đã đặt'), ('CANCELLED', 'Đã hủy')], default='AVAILABLE', help_text='Trạng thái khung giờ', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Địa điểm khám', max_length=255, null=True)),
                ('department', models.CharField(blank=True, help_text='Khoa/Phòng', max_length=100, null=True)),
                ('room', models.CharField(blank=True, help_text='Phòng khám', max_length=50, null=True)),
                ('duration', models.IntegerField(default=30, help_text='Thời lượng khám (phút)')),
                ('max_patients', models.IntegerField(default=1, help_text='Số lượng bệnh nhân tối đa')),
                ('current_patients', models.IntegerField(default=0, help_text='Số lượng bệnh nhân hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='appointments.doctoravailability')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('doctor_id', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Đang chờ'), ('WITH_NURSE', 'Đang với y tá'), ('WITH_DOCTOR', 'Đang khám với bác sĩ'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='WAITING', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.IntegerField(blank=True, help_text='ID người check-in (nhân viên)', null=True)),
                ('nurse_id', models.IntegerField(blank=True, help_text='ID y tá phụ trách', null=True)),
                ('vitals_recorded', models.BooleanField(default=False, help_text='Dấu hiệu sinh tồn đã được ghi nhận')),
                ('vitals_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_start_time', models.DateTimeField(blank=True, help_text='Thời gian bắt đầu khám với bác sĩ', null=True)),
                ('doctor_end_time', models.DateTimeField(blank=True, help_text='Thời gian kết thúc khám với bác sĩ', null=True)),
                ('waiting_time', models.IntegerField(blank=True, help_text='Thời gian chờ (phút)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Patient Visit',
                'verbose_name_plural': 'Patient Visits',
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], max_length=10)),
                ('scheduled_time', models.DateTimeField(help_text='Thời gian dự kiến gửi nhắc nhở')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ gửi'), ('SENT', 'Đã gửi'), ('FAILED', 'Gửi thất bại')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(help_text='Nội dung tin nhắn nhắc nhở')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Appointment Reminder',
                'verbose_name_plural': 'Appointment Reminders',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.appointmentreason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.timeslot'),
        ),
    ]
