# Generated by Django 4.2.7 on 2025-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_date',
            field=models.DateField(blank=True, help_text='Ngày kết thúc áp dụng lịch làm việc', null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Lịch làm việc có đang hoạt động hay không'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='recurring_pattern',
            field=models.CharField(choices=[('WEEKLY', 'Hàng tuần'), ('BIWEEKLY', 'Cách tuần'), ('MONTHLY', 'Hàng tháng'), ('CUSTOM', 'Tùy chỉnh')], default='WEEKLY', help_text='Mẫu lặp lại cho lịch làm việc', max_length=20),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_date',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu áp dụng lịch làm việc', null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Khung giờ có đang hoạt động hay không'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='source_type',
            field=models.CharField(choices=[('REGULAR', 'Từ lịch thường xuyên'), ('TEMPORARY', 'Từ lịch tạm thời'), ('MANUAL', 'Tạo thủ công')], default='REGULAR', help_text='Nguồn gốc của khung giờ', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('BOOKED', 'Đã đặt'), ('CANCELLED', 'Đã hủy'), ('BLOCKED', 'Bị khóa')], default='AVAILABLE', help_text='Trạng thái khung giờ', max_length=20),
        ),
    ]
