# Generated by Django 4.2.7 on 2025-04-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
