# Generated by Django 4.2.7 on 2025-04-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patientprofile_date_of_birth_and_more'),
        ('users', '0002_alter_patientprofile_fields'),
    ]

    operations = [
    ]
