# Generated by Django 4.2.7 on 2025-04-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250418_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='accepts_new_patients',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='availability_notes',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital_affiliations',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='research_publications',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_days',
            field=models.CharField(default='MON,TUE,WED,THU,FRI', help_text="Comma separated days, e.g., 'MON,TUE,WED,THU,FRI'", max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_hours',
            field=models.CharField(default='08:00-17:00', help_text="Format: '09:00-17:00'", max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(1, 'Level 1 - Basic Access'), (2, 'Level 2 - Standard Access'), (3, 'Level 3 - Enhanced Access'), (4, 'Level 4 - Advanced Access'), (5, 'Level 5 - Full Access')], default=1, help_text='1-5, with 5 being highest access'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='responsibilities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(default='Tiếng Việt', max_length=200),
        ),
        migrations.AlterField(
            model_name='insuranceproviderprofile',
            name='available_plans',
            field=models.CharField(default='Basic, Standard, Premium', help_text='Description of available insurance plans', max_length=500),
        ),
        migrations.AlterField(
            model_name='insuranceproviderprofile',
            name='service_areas',
            field=models.CharField(default='All Areas', help_text='Comma-separated list of service areas', max_length=500),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='equipment_expertise',
            field=models.CharField(blank=True, help_text='List of laboratory equipment the technician is proficient with', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='languages_spoken',
            field=models.CharField(default='Tiếng Việt', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='languages_spoken',
            field=models.CharField(default='Tiếng Việt', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='pharmacy_name',
            field=models.CharField(default='General Pharmacy', max_length=200),
        ),
    ]
