# Generated by Django 4.2.7 on 2025-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_doctorprofile_accepts_new_patients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='secondary_specialization',
            field=models.CharField(blank=True, choices=[('NOI_TIM_MACH', 'Chuyên khoa Tim mạch'), ('NOI_TIEU_HOA', 'Chuyên khoa Tiêu hóa'), ('NOI_HO_HAP', 'Chuyên khoa Hô hấp'), ('NOI_THAN', 'Chuyên khoa Thận - Tiết niệu'), ('NOI_TIET', 'Chuyên khoa Nội tiết'), ('NOI_THAN_KINH', 'Chuyên khoa Thần kinh'), ('NOI_DA_LIEU', 'Chuyên khoa Da liễu'), ('NOI_TONG_QUAT', 'Chuyên khoa Nội tổng quát'), ('NGOAI_CHINH_HINH', 'Chuyên khoa Chấn thương chỉnh hình'), ('NGOAI_TIET_NIEU', 'Chuyên khoa Tiết niệu'), ('NGOAI_THAN_KINH', 'Chuyên khoa Thần kinh'), ('NGOAI_LONG_NGUC', 'Chuyên khoa Lồng ngực - Mạch máu'), ('NGOAI_TIEU_HOA', 'Chuyên khoa Tiêu hóa'), ('NGOAI_TONG_QUAT', 'Chuyên khoa Ngoại tổng quát'), ('SAN_KHOA', 'Chuyên khoa Sản'), ('PHU_KHOA', 'Chuyên khoa Phụ khoa'), ('VO_SINH', 'Chuyên khoa Vô sinh - Hiếm muộn'), ('NHI_TONG_QUAT', 'Chuyên khoa Nhi Tổng quát'), ('NHI_TIM_MACH', 'Chuyên khoa Nhi Tim mạch'), ('NHI_THAN_KINH', 'Chuyên khoa Nhi Thần kinh'), ('NHI_SO_SINH', 'Chuyên khoa Sơ sinh'), ('MAT', 'Chuyên khoa Mắt'), ('TAI_MUI_HONG', 'Chuyên khoa Tai Mũi Họng'), ('RANG_HAM_MAT', 'Chuyên khoa Răng Hàm Mặt'), ('TAM_THAN', 'Chuyên khoa Tâm thần'), ('UNG_BUOU', 'Chuyên khoa Ung bướu'), ('DA_KHOA', 'Đa khoa'), ('KHAC', 'Chuyên khoa khác')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('NOI_TIM_MACH', 'Chuyên khoa Tim mạch'), ('NOI_TIEU_HOA', 'Chuyên khoa Tiêu hóa'), ('NOI_HO_HAP', 'Chuyên khoa Hô hấp'), ('NOI_THAN', 'Chuyên khoa Thận - Tiết niệu'), ('NOI_TIET', 'Chuyên khoa Nội tiết'), ('NOI_THAN_KINH', 'Chuyên khoa Thần kinh'), ('NOI_DA_LIEU', 'Chuyên khoa Da liễu'), ('NOI_TONG_QUAT', 'Chuyên khoa Nội tổng quát'), ('NGOAI_CHINH_HINH', 'Chuyên khoa Chấn thương chỉnh hình'), ('NGOAI_TIET_NIEU', 'Chuyên khoa Tiết niệu'), ('NGOAI_THAN_KINH', 'Chuyên khoa Thần kinh'), ('NGOAI_LONG_NGUC', 'Chuyên khoa Lồng ngực - Mạch máu'), ('NGOAI_TIEU_HOA', 'Chuyên khoa Tiêu hóa'), ('NGOAI_TONG_QUAT', 'Chuyên khoa Ngoại tổng quát'), ('SAN_KHOA', 'Chuyên khoa Sản'), ('PHU_KHOA', 'Chuyên khoa Phụ khoa'), ('VO_SINH', 'Chuyên khoa Vô sinh - Hiếm muộn'), ('NHI_TONG_QUAT', 'Chuyên khoa Nhi Tổng quát'), ('NHI_TIM_MACH', 'Chuyên khoa Nhi Tim mạch'), ('NHI_THAN_KINH', 'Chuyên khoa Nhi Thần kinh'), ('NHI_SO_SINH', 'Chuyên khoa Sơ sinh'), ('MAT', 'Chuyên khoa Mắt'), ('TAI_MUI_HONG', 'Chuyên khoa Tai Mũi Họng'), ('RANG_HAM_MAT', 'Chuyên khoa Răng Hàm Mặt'), ('TAM_THAN', 'Chuyên khoa Tâm thần'), ('UNG_BUOU', 'Chuyên khoa Ung bướu'), ('DA_KHOA', 'Đa khoa'), ('KHAC', 'Chuyên khoa khác')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='department',
            field=models.CharField(choices=[('KHOA_NOI', 'Khoa Nội'), ('KHOA_NGOAI', 'Khoa Ngoại'), ('KHOA_SAN', 'Khoa Sản - Phụ khoa'), ('KHOA_NHI', 'Khoa Nhi'), ('KHOA_CAP_CUU', 'Khoa Cấp cứu'), ('KHOA_XET_NGHIEM', 'Khoa Xét nghiệm'), ('KHOA_CHAN_DOAN_HINH_ANH', 'Khoa Chẩn đoán hình ảnh'), ('KHOA_MAT', 'Khoa Mắt'), ('KHOA_TMH', 'Khoa Tai Mũi Họng'), ('KHOA_RHM', 'Khoa Răng Hàm Mặt'), ('KHOA_UNG_BUOU', 'Khoa Ung bướu'), ('KHOA_HOI_SUC', 'Khoa Hồi sức tích cực (ICU)'), ('KHOA_KHAC', 'Khoa khác')], max_length=100),
        ),
    ]
