# Generated by Django 4.2.7 on 2025-04-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorprofile_secondary_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceinformation',
            name='member_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
