# Generated by Django 4.2.7 on 2025-04-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_insuranceinformation_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
